WebAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      DesiredCapacity: 2
      MaxSize: 4
      MinSize: 2
      VPCZoneIdentifier:
        - !Ref PublicSubnetA
        - !Ref PublicSubnetB
      TargetGroupARNs:
        - !Ref WebTargetGroup
      LaunchTemplate:
        LaunchTemplateId: !Ref WebLaunchTemplate
        Version: "$Latest"
      Tags:
        - Key: Name
          Value: ASG-WebServer
          PropagateAtLaunch: true

  ScaleByCPU:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AutoScalingGroupName: !Ref WebAutoScalingGroup
      PolicyType: TargetTrackingScaling
      TargetTrackingConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ASGAverageCPUUtilization
        TargetValue: 50.0

  MyTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: NginxTask
      NetworkMode: bridge
      RequiresCompatibilities:
        - EC2
      ContainerDefinitions:
        - Name: nginx-container
          Image: nginxdemos/hello
          Cpu: 256
          Memory: 256
          PortMappings:
            - ContainerPort: 80
              HostPort: 80
              Protocol: tcp

  MyECSService:
    Type: AWS::ECS::Service
    DependsOn:
      - WebAutoScalingGroup
      - ScaleByCPU
      - EC2SecurityGroup
      - WebLaunchTemplate
      - WebTargetGroup
      - ALBSecurityGroup
      - MainVPC
      - PublicSubnetA
      - PublicSubnetB
      - InternetGateway
      - AttachGateway
      - PublicRouteTable
      - DefaultRoute
      - SubnetARouteTableAssociation
      - SubnetBRouteTableAssociation
      - WebLoadBalancer
      - HTTPListener
    Properties:
      Cluster: !Ref MyECSCluster
      DesiredCount: 1
      LaunchType: EC2
      TaskDefinition: !Ref MyTaskDefinition