Resources:
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: SG-EC2
      GroupDescription: Permite tráfego apenas do ALB e SSH local
      VpcId: !Ref MainVPC
      SecurityGroupIngress:
        - Description: HTTP do Load Balancer
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref ALBSecurityGroup
        - Description: SSH do IP local
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: YOUR_PUBLIC_IP/32  # Substitua pelo seu IP
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: 0
          ToPort: 0
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: SG-EC2

  WebLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: LT-WebServer
      LaunchTemplateData:
        ImageId: !Ref AmazonLinuxAMI
        InstanceType: t2.micro
        KeyName: !Ref KeyPairName
        SecurityGroupIds:
          - !Ref EC2SecurityGroup
        UserData: !Base64 |
          #!/bin/bash
          # Substitua pelo conteúdo do seu script userdata.sh
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: WebServer

  AmazonLinuxAMI:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

  WebTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: TG-Web
      Port: 80
      Protocol: HTTP
      VpcId: !Ref MainVPC
      HealthCheckPath: /